#!/bin/sh
ROOT=$PWD

# cd $ROOT
# rm -rf clasp-2.0-R4092
# tar xvzf clasp-2.0-R4092.tar.gz
# cd clasp-2.0-R4092
# ./configure.sh --strip
# cd build/release
# make
# cp bin/clasp $ROOT/clasp

cd $ROOT
rm -rf claspmt-2.0-R4095-patched
tar xvzf claspmt-2.0-R4095-patched.tar.gz
cd claspmt-2.0-R4095-patched
./configure.sh --with-mt TBB_INCLUDE=$HOME/tools64/include/tbb TBB_LIB=$HOME/tools64/lib64
cd build/release_mt
make
cp bin/clasp $ROOT/claspmt
