#!/bin/sh
ROOT=$PWD

rm -rf trove-2.1.0 constellation brtzsnr-structure-3832ec0
rm -rf  ~/.m2/repository/ibis/ ~/.m2/repository/trove

mkdir constellation
cd constellation
unzip ../constellation.zip
ant clean
ant
mvn install:install-file -Dfile=lib/constellation-0.7.0.jar -Dpackaging=jar -DgroupId=ibis -DartifactId=constellation -Dversion=0.7.0

cd $ROOT
tar xzf trove-2.1.0.tar.gz
cd trove-2.1.0
ant clean
ant
mvn install:install-file -Dfile=lib/trove-2.1.0.jar -Dpackaging=jar -DgroupId=trove -DartifactId=trove -Dversion=2.1.0

cd $ROOT
unzip brtzsnr-structure-sc11-0-g3832ec0.zip
cd brtzsnr-structure-3832ec0

mvn clean
mvn site
mvn compile test
mvn assembly:assembly

#
